SRC += amadeus.c

LTO_ENABLE = yes
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
SEND_STRING_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
